# Generated by Django 3.0.6 on 2020-07-14 03:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=30, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de Empleado',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellido(s)')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('adress', models.CharField(max_length=100, verbose_name='Direccion')),
                ('job', models.CharField(choices=[('0', 'CEO'), ('1', 'Gerente'), ('2', 'Repartidor'), ('3', 'Empaquetador'), ('4', 'Contador'), ('5', 'Vendedor'), ('6', 'Trabajador(a) Social'), ('7', 'Otro')], max_length=1, verbose_name='Trabajo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleados')),
                ('hoja_vida', ckeditor.fields.RichTextField(verbose_name='Hoja De Vida')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.Departamento')),
                ('habilidades', models.ManyToManyField(to='persona.Habilidades')),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleados de la Empresa',
                'ordering': ['id'],
                'unique_together': {('first_name', 'last_name', 'job', 'departamento')},
            },
        ),
    ]
